# Generated by Django 3.1.12 on 2026-01-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('attendance_date', models.DateTimeField(blank=True, null=True)),
                ('session', models.IntegerField(default=0)),
                ('therapy_details', models.TextField(blank=True, null=True)),
                ('therapy_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_details', models.TextField(blank=True, null=True)),
                ('consultant_doctor', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'milestone_backend_patientattendance',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_child', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mail_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_visit', models.TextField(blank=True, null=True)),
                ('duration_of_symptoms', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_treatment_done', models.CharField(blank=True, max_length=200, null=True)),
                ('source_of_referral', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'milestone_backend_registration',
            },
        ),
    ]
